# Mandatory settings

baseurl: /
name: "Continuous Improvement"
paginate: 25
paginate_path: "/posts/page/:num/"
url: # add site url http://example.com/
blog_theme: light # Or use dark
plugins: [jekyll-youtube]

# Optional settings

discus_identifier: 'lenlabs' # Add your Disqus identifier
ga_analytics: 'UA-80058083-2' # Add your GA Tracking Id
rss_enabled: true # Change to false if not
social:
  gravatar: 'e2a8ead7f70ffafa95672566f2999c8a'
  dribbble: # Add your Dribbble link
  facebook: # Add your Facebook link
  github: 'https://github.com/0xlen'
  linkedin: # Add your LinkedIn link
  twitter: # Add your Twitter handle
  email: 'eason@easoncao.com'
  bitcoin: # Add your Bitcoin link or address

# Important settings (change at own risk)

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

assets:
  compress:
    css: true
    js: true
  features:
    automatic_img_size: false
  sources:
    - _assets/bower
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
permalink: posts/:slug
